### ISSUE TITLE
Not fully support GitHub Flavored Markdown 

### ISSUE THREAD

**Issue by oska874** [jamiemcg/Remarkable#20]
When I start to write markdown file , its preview is different from github website. like : 

```

---
tags : u-boot 

---
```

and : 

```
xxx
===
```

these two sentence show different result in remarkable and github website.

**Comment by MrCelticFox** [comment]
If I may add to this, I also noticed this program doesn't support the use of emojis (such as :8ball: for example, obtained by typing `:8ball:`) which are supported in GitHub flavoured markdown.

**Comment by MrCelticFox** [comment]
Another feature that is only partially implemented is tables: center and right align don't work, everything is left aligned.

Using this markdown:
```markdown
| Left | Center | Right |
| --- | :---: | ---: |
| a | a | a |
| bb | bb | bb |
| cccc | ccc | ccc |
```
should generate the following table:

| Left | Center | Right |
| --- | :---: | ---: |
| a | a | a |
| bb | bb | bb |
| cccc | ccc | ccc |

but instead it looks like this:
![incorrect_table](https://cloud.githubusercontent.com/assets/6884288/19346492/8333d87a-913b-11e6-8259-700536a7b30b.png)

**Comment by bijanbina** [comment]
@MrCelticFox I'm have the same problem, 
can you please share your custom stylesheet file

**Comment by bijanbina** [comment]
Don't bother
here is the fixed stylesheet can put inside /usr/lib/python3.5/site-packages/remarkable/styles.py
```
github = 'body,table tr{background-color:#fff}table tr td,table tr th{border:1px solid #ccc;text-align:left;padding:6px 13px;margin:0}pre code,table,table tr{padding:0}hr,pre code{background:0 0}body{font:16px Helvetica,Arial,sans-serif;line-height:1.4;color:#333;word-wrap:break-word;padding:10px 15px}strong,table tr th{font-weight:700}h1{font-size:2em;margin:.67em 0;text-align:center}h2{font-size:1.75em}h3{font-size:1.5em}h4{font-size:1.25em}h1,h2,h3,h4,h5,h6{font-weight:700;position:relative;margin-top:15px;margin-bottom:15px;line-height:1.1}h1,h2{border-bottom:1px solid #eee}hr{height:0;margin:15px 0;overflow:hidden;border:0;border-bottom:1px solid #ddd}a{color:#4183C4}a.absent{color:#c00}ol,ul{padding-left:15px;margin-left:5px}ol{list-style-type:lower-roman}table tr{border-top:1px solid #ccc;margin:0}table tr:nth-child(2n){background-color:#aaa}table tr td :first-child,table tr th :first-child{margin-top:0}table tr td:last-child,table tr th :last-child{margin-bottom:0}img{max-width:100%}blockquote{padding:0 15px;border-left:4px solid #ccc}code,tt{margin:0 2px;padding:0 5px;white-space:nowrap;border:1px solid #eaeaea;background-color:#f8f8f8;border-radius:3px}pre code{margin:0;white-space:pre;border:none}.highlight pre,pre{background-color:#f8f8f8;border:1px solid #ccc;font-size:13px;line-height:19px;overflow:auto;padding:6px 10px;border-radius:3px}'
```

**Comment by vphantom** [comment]
FYI @bijanbina the CSS you posted is exactly the one found in `remarkable/styles.py` as of commit  3848a70d so I guess this was fixed on August 6th (version 1.87).  I'm guessing you're still on version 1.75?

**Comment by bijanbina** [comment]
I doubt that.
I'm on Arch Linux running version 1.87 installed from AUR. The [file](https://github.com/jamiemcg/Remarkable/blob/3848a70d82bff860d5b8d13a43ed36fd0167e0b0/remarkable/styles.py) you have mentioned seems to me still have this bug inside(the left alignment and ....).
can you check it again?

**Comment by vphantom** [comment]
Thanks @bijanbina. I should note that I'm not actually a maintainer here, just a fan.  I was going to create a pull request with your modified CSS, but because they're on a single line they're very difficult to compare.  Do you have details on the specific changes you did?  For example, the removal of `body` seems counter-intuitive to me.

**Comment by bijanbina** [comment]
If I be blunt the hacking is too dirty to understand and I suggest that it be improved before comitment.
I realy appreciate the pull request and hope it gets merged soon.
The changed was made based on github [stylesheet](https://assets-cdn.github.com/assets/github-f1dd95db316b03c6d429dd35926fdf5b6520abdff62d481127e84cc9ab7460d0.css):334

Specifically following lines
```
.markdown-body table {
	display:block;
	width:100%;
	overflow:auto
}
.markdown-body table th {
	font-weight:bold
}
.markdown-body table th,.markdown-body table td {
	padding:6px 13px;
	border:1px solid #ddd
}
.markdown-body table tr {
	background-color:#fff;
	border-top:1px solid #ccc
}
.markdown-body table tr:nth-child(2n) {
	background-color:#f8f8f8
}
```
As it seems a little odd you can double check how I found these stylesheet by
1. Open firefox (or other browser)
2. Browse [Github Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
3. Use "Inspect Element" on table
4. Extract corresponding stylesheet

**Comment by vphantom** [comment]
Looks good. I'll give @jamiemcg a chance to react and if things stay quiet I'll attempt a pull request which would include expanding the stylesheets in `remarkable/styles.py` into a clearer multiple-line format.

**Comment by vphantom** [comment]
Done in pull request #90.

**Comment by bijanbina** [comment]
@vphantom WoW.... Looks nice to me (but it may not sounds great to un minify the css to the developer)
still your new stylesheet lacks the following lines
```
table {
    border-collapse:collapse
}
```
It is something that I found neccessary in markdown stylesheet (so it's not a surprise that it didn't appear on github page) to fix the space between each cell.
At a glance the commitment seems to have no conflict however I suggest that recheck the new stylesheet at the runtime for any remains conflicts.
As a last note: what's the purpuse of ` text-align: left;` on [remarkable/styles.py](https://github.com/jamiemcg/Remarkable/pull/90/commits/4ca762a92ca69815ece01300d3f9b88e2d7a8064#diff-77e287e9727aa050c2ed626c8fc788a2R477):477
Shouldn't it be `text-align: center` or be avoided?

**Comment by vphantom** [comment]
I'll see if I can amend my PR (never tried that before) with the missing collapse, which is indeed a good idea.

The left alignment left for `th` was originally also imposed on `td` which overrode the cells' attributes.  I kept it for `th` based on [the examples](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables) which are not very clear for headers.  After further experimentation you're absolutely right, it should be removed entirely.

**Comment by bijanbina** [comment]
hope it'll be merged :)

**Comment by MrCelticFox** [comment]
@bijanbina I didn't bother hacking the source or rebuilding ^^ I just copy pasted the Github style into the custom style section and change the appropriate lines. This suits me because I add and remove bits depending on what report I'm writing, so for example sometimes I need to highlight rows in blocks of two or three, and sometimes not at all, other times I might put two tables next to each other.  Glad you got it fixed :+1:

**Comment by Julianoe** [comment]
I'm adding my 👍 for emoji support
